Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [1]:
from sklearn import datasets
import numpy as np
import pandas as pd

iris_raw_ds = datasets.load_iris(as_frame= True)
iris_raw_df = iris_raw_ds.frame
iris_raw_data = iris_raw_ds.data
print(iris_raw_data)
#1. Extract feature matrix as NumPy array
# Feature matrix as NumPy array
iris_raw_data_np = iris_raw_data.to_numpy()
print(iris_raw_data_np)


     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [

In [2]:
# 2. Compute:
# Mean
# Median
# Standard deviation
# Variance (for each feature)

# print(type(iris_raw_data))
# print(iris_raw_data.columns)
# print(iris_raw_data.shape[0])
# print(iris_raw_data['sepal length (cm)'].count())
for i in iris_raw_data.columns:
    mean = iris_raw_data[i].sum()/iris_raw_data.shape[0]
    print(f"Mean of column {i} is : {mean.round(2)}")
    median = iris_raw_data[i].median()
    print(f"Median of column {i} is : {median}")
    sd = iris_raw_data[i].std()
    print(f"Standard deviation of column {i} is : {round(sd,2)}")
    var = iris_raw_data[i].var()
    print(f"Variance deviation of column {i} is : {round(var,2)}")

    

Mean of column sepal length (cm) is : 5.84
Median of column sepal length (cm) is : 5.8
Standard deviation of column sepal length (cm) is : 0.83
Variance deviation of column sepal length (cm) is : 0.69
Mean of column sepal width (cm) is : 3.06
Median of column sepal width (cm) is : 3.0
Standard deviation of column sepal width (cm) is : 0.44
Variance deviation of column sepal width (cm) is : 0.19
Mean of column petal length (cm) is : 3.76
Median of column petal length (cm) is : 4.35
Standard deviation of column petal length (cm) is : 1.77
Variance deviation of column petal length (cm) is : 3.12
Mean of column petal width (cm) is : 1.2
Median of column petal width (cm) is : 1.3
Standard deviation of column petal width (cm) is : 0.76
Variance deviation of column petal width (cm) is : 0.58


In [3]:
# 3. Identify: Which feature has highest variability and why it matters in ML
#Ans: Veriance is used to check whether a feature is useful for ML training or not if the veriance is constant, that means if the veriance is zero or near zero then that feature is not useful.
#     Similarly SD shows what is the average distance of a sample from the mean for that feature. So high SD is features are good to concider for ML traning.
#Petal length (cm) has the highest variability in the Iris dataset because it has the largest standard deviation (1.7653) and variance (3.1163). But high variability alone does not guarantee usefulness.
iris_raw_ds = datasets.load_iris(as_frame= True)
X = iris_raw_ds.data # All data with all the features except target
std = X.std()
var = X.var()
mean = X.mean()
# print(f"std: {std}")
# print(f"var: {var}")
# print(f"mean: {mean}")
output = pd.DataFrame({'mean':X.mean(), 'std':std, 'var':var}).sort_values(by = "std", ascending=False)
output_sorted = output.sort_values(by = "std", ascending=False)
print(f"output: {output_sorted}")


output:                        mean       std       var
petal length (cm)  3.758000  1.765298  3.116278
sepal length (cm)  5.843333  0.828066  0.685694
petal width (cm)   1.199333  0.762238  0.581006
sepal width (cm)   3.057333  0.435866  0.189979


In [4]:
# 4. Convert any one feature into shape (n,1) and explain why ML models expect this format
## Most algorithms in ML, expects the input features to be in 2D array. This is to keep consistency, avoid ambiguity, because a 1D array can be inferred as "one feature with n samples or one sample with n features."
## Also most of the ML models use matrix operations internally, so 2D array is really convinient.
OneD_array = iris_raw_data["petal length (cm)"] #its a series and its represented as 1D array.
print(OneD_array.shape)
TwoD_array = iris_raw_data[["petal length (cm)"]] # its a dataframe and its rpresented as 2D array.
print(TwoD_array.shape)

(150,)
(150, 1)


Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [ ]:
#Extract last two features and first 100 rows  
iris_raw_ds = datasets.load_iris(as_frame= True)
iris_raw_data = iris_raw_ds.data
iris_raw_data_np = iris_raw_data.to_numpy()
print(iris_raw_data_np[:100,-2:])
print(iris_raw_data.iloc[:100,-2:])
print(iris_raw_data_np[:100, -2:].shape) 
print(iris_raw_data.iloc[:100, -2:].shape) 


[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [ ]:
# boolean masking means keep only the data where condition is true.
print(f"Column list: {iris_raw_data.columns}")
data_set_mean = iris_raw_data_np.mean().round(2)
# print(f"Dataset mean: {data_set_mean}")
mask = iris_raw_data_np[:,2] > data_set_mean
# print(f"Mask: {mask}")
filtered_data = iris_raw_data_np[mask]
# print(f"Filtered data: {filtered_data}")

# using pands df 
mask = iris_raw_data["petal length (cm)"]> 5
print(f"Mask: {mask}")
filtered_data = iris_raw_data[mask]
print(f"Filtered data: {filtered_data}")

Column list: Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
Mask: 0      False
1      False
2      False
3      False
4      False
       ...  
145     True
146    False
147     True
148     True
149     True
Name: petal length (cm), Length: 150, dtype: bool
Filtered data: (42, 4)


In [27]:
print(f"Selected samples {filtered_data.shape[0]}")

Selected samples 42


Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [34]:
iris_ds = datasets.load_iris(as_frame=True)
iris_np = iris_ds.data.to_numpy()
mean_mu = iris_np.mean(axis=0)
std_sigma = iris_np.std(axis=0, ddof=0)
standardised_np_arr = (iris_np - mean_mu)/std_sigma
print(standardised_np_arr)

print("Means after scaling:", standardised_np_arr.mean(axis=0))
print("Stds after scaling :", standardised_np_arr.std(axis=0, ddof=0))

#we calculate standard deviation based on the logic that we will know that how the values are spread across the mean and the single digit standard variation for a column means that its the average distance of  of a value in that feature from the the mean.
# Mean (μ\muμ) gives the “center” of a feature (column).
# Std (σ\sigmaσ) tells the “typical/average distance” of values from that mean (spread).
# Standardization converts every value into a common scale so different features become comparable.
# The standardized value (z‑score) represents how far a point is from the mean, measured in units of standard deviation.
# the center becomes zero on every axis (feature axis), but it’s better to think of it as the mean point (centroid) of the dataset shifting to the origin.


[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [41]:
import seaborn as sns
import pandas as pd
titanic_ds = sns.load_dataset('titanic')
print(titanic_ds.head())
print(titanic_ds.tail())
print(titanic_ds.info())
print(titanic_ds.describe())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S

In [57]:
titanic_ds.dtypes
# num_columns = [i for i in titanic_ds.select_dtypes(["int64", "float64"]).columns]
num_columns = titanic_ds.select_dtypes(["int64", "float64"]).columns.tolist()
print(f"Numeric columns: {num_columns}")
# cat_columns = [i for i in titanic_ds.select_dtypes(["object", "float64", "category", "bool"])]
cat_columns = titanic_ds.select_dtypes(["object", "category", "bool"]).columns.tolist()
print(f"Numeric columns: {cat_columns}")

# Identify missing count per column
missing_nums = titanic_ds[num_columns].isna().sum()
missing_cats = titanic_ds[cat_columns].isna().sum()

print("Missing values in numeric columns:\n", missing_nums[missing_nums > 0])
print("\nMissing values in categorical columns:\n", missing_cats[missing_cats > 0])


total_missing_num = titanic_ds[num_columns].isna().sum().sum()
total_missing_cat = titanic_ds[cat_columns].isna().sum().sum()

print(f"Total missing in numeric columns: {total_missing_num}") # 177
print(f"Total missing in categorical columns: {total_missing_cat}") #2+688+2 = 692

# the concept id isna() will retrun True and False and first sum will treat the True as 1 and Flase as 0 .

# We need to identify the feature data type because, machines do not understand the normal data like humans do, they understands numbers good.
# When we know the data type, then we can decide that on which column/feature we need to apply standardisation/normalization, encoding.



Numeric columns: ['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']
Numeric columns: ['sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']
Missing values in numeric columns:
 age    177
dtype: int64

Missing values in categorical columns:
 embarked         2
deck           688
embark_town      2
dtype: int64
Total missing in numeric columns: 177
Total missing in categorical columns: 692


Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [70]:
#Female passemgers in 1st class 
titanic_ds.head(3)
f_in_1st = titanic_ds[(titanic_ds["sex"] == "female") & (titanic_ds["class"] == "First")]

In [97]:
# Survival rate 
# titanic_ds.head(3)
# total_survived = titanic_ds[titanic_ds["survived"] == 1].shape[0]
# total_passenger = titanic_ds.shape[0]
# survival_rate = (total_survived/total_passenger) * 100
total_survived = (titanic_ds["survived"] == 1).sum()
total_passenger = titanic_ds["survived"].count()
survival_rate = (total_survived/total_passenger) * 100
# print(f"Total survived: {round(survival_rate, 2)}")

#survival rate by this group
survival_rate = titanic_ds.groupby(["sex","class"],observed=True)["survived"].mean()
# print(f"Type: {type(survival_rate)}")
# print(f"{survival_rate}")
survival_rate_by_group =  survival_rate.loc["female", "First"]
print(round(survival_rate_by_group,2))




0.97


Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight